export const tableOption = {
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "column": [
	  {
      "type": "input",
      "label": "设备ID",
      "prop": "deviceId"
    },	  {
      "type": "input",
      "label": "设备标识",
      "prop": "deviceMark"
    },	  {
      "type": "input",
      "label": "设备型号",
      "prop": "deviceModel"
    },	  {
      "type": "input",
      "label": "平台类型:1-UNKNOWN,2-iOS,3-Android",
      "prop": "deviceType"
    },	  {
      "type": "input",
      "label": "制造商",
      "prop": "manufacture"
    },	  {
      "type": "input",
      "label": "绑定标识",
      "prop": "bindingFlag"
    },	  {
      "type": "input",
      "label": "安全状态:1-正常,2-root,3-越狱",
      "prop": "safeType"
    },	  {
      "type": "input",
      "label": "最后一次使用时间",
      "prop": "lastUseTime",
      "width": '160'
    },	  {
      "type": "input",
      "label": "最后一次登录时间",
      "prop": "lastLoginTime",
      "width": '160'
    },	  {
      "type": "input",
      "label": "最后一次登录IP",
      "prop": "lastLoginAddr"
    },	  {
      "type": "input",
      "label": "屏幕宽度",
      "prop": "scrnWidth"
    },	  {
      "type": "input",
      "label": "屏幕高度",
      "prop": "scrnHeight"
    },	  {
      "type": "input",
      "label": "分辨率",
      "prop": "scrnResolution"
    },	  {
      "type": "input",
      "label": "屏幕dpi",
      "prop": "scrnDpi"
    },	  {
      "type": "input",
      "label": "屏幕比率",
      "prop": "scrnRate"
    },	  {
      "type": "input",
      "label": "系统名称",
      "prop": "systemName"
    },	  {
      "type": "input",
      "label": "系统版本",
      "prop": "systemVersion"
    },	  {
      "type": "input",
      "label": "系统引擎",
      "prop": "systemAgent"
    },	  {
      "type": "input",
      "label": "MAC",
      "prop": "macAddr"
    },	  {
      "type": "input",
      "label": "唯一标识",
      "prop": "identification"
    },	  {
      "type": "input",
      "label": "序列号",
      "prop": "serial"
    },	  {
      "type": "input",
      "label": "设备名称",
      "prop": "deviceName"
    },	  {
      "type": "input",
      "label": "手机号码",
      "prop": "mobileNumber"
    },	  {
      "type": "input",
      "label": "供应商名称",
      "prop": "operatorName"
    },	  {
      "type": "input",
      "label": "供应商代码",
      "prop": "operatorCode"
    },	  {
      "type": "input",
      "label": "是否模拟器",
      "prop": "simulatorFlag"
    },	  {
      "type": "input",
      "label": "是否宽屏",
      "prop": "landscapeFlag"
    },	  {
      "type": "input",
      "label": "是否平板",
      "prop": "tabletFlag"
    },	  {
      "type": "input",
      "label": "是否设置密码",
      "prop": "setPinNumberFlag"
    },	  {
      "type": "input",
      "label": "是否设置指纹",
      "prop": "setFingerPrintFlag"
    },	  {
      "type": "input",
      "label": "是否设置面容",
      "prop": "setFacePrintFlag"
    },	  {
      "type": "input",
      "label": "删除标记",
      "prop": "delFlag"
    },	  {
      "type": "input",
      "label": "创建",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime",
      "width": '160'
    }  ]
}
